global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "reth"
    static_configs:
      - targets: ["10.200.0.10:9001"]   # reth metrics

  - job_name: "lighthouse"
    static_configs:
      - targets: ["10.200.0.11:5054"]   # lighthouse metrics
